### ISSUE TITLE
Shebang not portable

### ISSUE THREAD

**Issue by sci4me** [SquidDev/urn#10]
When I compile on my laptop with --shebang, I get `#!/usr/bin/env C:\Users\sci4me\AppData\Local\LuaVM\versions\5.1\lua.exe` whereas I get a totally different path on my desktop. Should it not just generate `#!/usr/bin/env lua` or something?

**Comment by SquidDev** [comment]
We currently use the existing interpreter as that's really the only thing we can guarantee existing (people may have `lua5.3` but not `lua`). Windows is a bit odd with path resolution (and everything else :p), so I'm not sure what to do there.

A sort of alternative would be to specify a custom path using `--shebang=lua`. That will always result in `#!/usr/bin/env lua`.
