### ISSUE TITLE
allow different file extensions for source files

### ISSUE THREAD

**Issue by ghubthrowaway** [SquidDev/urn#11]
I use urn for scripts and in my script-dir are also files written in common lisp. Even if all my CL files end in .cl, it is still confusing when some files end in .lisp, especially if I want to share it someday. Imo this makes sense for sharing code in general to avoid confusion.

Unless there are any hard problems with making the file extension variable, it would be neat, if you could implement it. If you got no time / don't care enough, but would accept a pull request I might look into it as well and create one.

Alternatively changing it to .urn would also fix the issue, but this would afaik conflict with the current urn code base.

**Comment by SquidDev** [comment]
I've changed it to search for `.lisp`, `.cl` and `.urn` files. I'm slightly iffy about `.cl` as we're a common lisp implementation, but I guess it won't cause any harm. 

Thanks for the report. It's always nice to see people using Urn!

**Comment by ghubthrowaway** [comment]
thanks for the fast fix.
