### ISSUE TITLE
matching of quoted symbols

### ISSUE THREAD

**Issue by srctxt** [SquidDev/urn#13]
hi,
It seems like 'case' can match keywords (:key) cannot match quoted symbols ('sym). I think it would be nice if that would work too.

```
(define mycol 'Blue)

(case mycol
  ('Blue (putstr "blueeee"))
  (_ (putstr "deffff")))
```

**Comment by SquidDev** [comment]
For various reasons, you just write the symbol without the quote in order to pattern match on it:

```cl
(case 'Blue
  [Blue "Is blue"] ;; Matches the symbol Blue
  [?other (pretty other)]) ;; Prefixing with a `?` will act as a capture.
```

The docs aren't entirely clear on this point - I'll see what I can do about that.
