### ISSUE TITLE
How to join two strings?

### ISSUE THREAD

**Issue by srctxt** [SquidDev/urn#14]
Is there something simpler then string/concat like 

`(join "hello " world)`

here is my "fix":

```
(defmacro join (&strings)
   `(string/concat (list ,@strings) ""))
```

is there something better?

**Comment by SquidDev** [comment]
Urn just uses Lua's string concatenation operator:

```cl
(.. "foo" "bar" "baz")
;; "foobarbaz"
```

There's also a [`format` function](http://urn-lang.com/docs/lib.data.format.html#format) for more advanced string formatting. For instance:

```cl
(with (x "bar")
  (format nil "foo{#x}baz"))
;; "foobarbaz" again.
```

**Comment by srctxt** [comment]
thanks alot, I struggle a bit with the documentation. I don't want to complain since you made already a huge effort documenting all libraries. My problem is finding stuff ...

**Comment by SquidDev** [comment]
Yeah, I'm aware that the documentation isn't the most accessible. The trouble is that I know where everything is, so it's rather hard to know what other people need - any feedback is welcome!

**Comment by srctxt** [comment]
I thing that would really really help: one big static index site, eg:

https://www.gnu.org/software/guile/manual/html_node/R5RS-Index.html

I work a lot with indexes such as the above. The more words (tags, keywords) in it the better.

Why: Ctrl+f

**Comment by SquidDev** [comment]
There's the [prelude](http://urn-lang.com/docs/lib.prelude.html) documentation file, which includes all symbols in the default scope. Not that would help in this case as `..` isn't actually documented :/.

I can look into generating some sort of index file for *all* symbols though, that would be useful.

**Comment by srctxt** [comment]
An index would be nice, may I suggest to include the title and/or library name and subtitle, eg:

```
A
- accumulate-with (core/list: List manipulation functions)
```

**Comment by SquidDev** [comment]
Closing in favour of #15.
