### ISSUE TITLE
Create an documentation index

### ISSUE THREAD

**Issue by srctxt** [SquidDev/urn#15]
An index would be nice, something in the form of
[ name ] ([short description] - [ library name] )

Example for an entry in the alphabetic index:
```
A
- accumulate-with (A composition of reduce and map. - core/list)
- ...
```

And also a short overview over the libraries:
```
Libraries
-core/list: List manipualtion functions

**Comment by SquidDev** [comment]
A couple of things which need considering:

 - Symbols may be exported from multiple modules. For instance, `+` is defined in `lua/basic`, and exported from `prelude`, `core/prelude` and `core/base`. This information might be useful to have, but could also end up pretty cluttered.
 - On a similar node, symbols may have multiple names. For instance, `concat` and `string/concat` point to the same name. I don't think this is an issue, but worth bearing in mind.
 - The inverse also applies: multiple symbols may have the same name. For instance, `lua/math`, `lua/io` and `core/base` all define a `type` symbol. We will have to make it clear how these are different symbols.

**Comment by SquidDev** [comment]
I've [made a start](https://gitlab.com/urn/urn/merge_requests/92) on this ([preview can be found here](https://gist.github.com/SquidDev/b52b5891c22a2e01d779b0539d838ff3)). Any feedback on the design, information provided, etc... is welcome.

**Comment by heddwch** [comment]
🍆

**Comment by SquidDev** [comment]
The [index is now live](http://urn-lang.com/docs/). Any feedback is welcome (I'm aware there are a couple of styling issues).
