### ISSUE TITLE
Create a PKGBUILD file and publish urn as a AUR package

### ISSUE THREAD

**Issue by ryukinix** [SquidDev/urn#16]
I and some friends (@kress95) have interests to have a package of `urn` for Arch Linux. We can build this as well, this issue is to track this implementation and if someone can contribute with this.

Thanks for making urn! It's a awesome project.

## Roadmap
- [x] list dependencies
- [x] write a PKGBUILD
- [x] publish it on AUR

**Comment by SquidDev** [comment]
I've put together a basic PKGBUILD ([see here](https://gitlab.com/urn/urn/merge_requests/105)). It just pulls from the repo, as I'm not sure it's worth having a separated versioned package as well.

Whilst it works, I'm sure there's something I'm missing, so feedback is welcome :).

**Comment by ryukinix** [comment]
This is a really nice start! Thanks for the fast implementation @SquidDev. I only saw that you prefer use GitLab instead GitHub after create this issue. I hope you don't mind to continue to track this issue here.

There is a one thing that we, I and @kress95 was thinking about it.... How we can handle the external packages of the urn language? For instance, I like to use the love2d-bindings wrote [here](https://gitlab.com/Lignum/urn-love2d-bindings) and I don't want to tweak the compiler every moment that I use a new package. So before you write the PKGBUILD I was designing the file tree for the `urn-lang` on my system:

```
/usr/lib/urn/core/ :: this repo
/usr/lib/urn/lib/ :: third-party packages
/usr/bin/urn :: compiler

Where /usr/bin/urn:
#!/bin/sh
/usr/lib/urn/core/urn/bin/urn.lua -i "/usr/lib/urn/packages/?" $@
```

If I install the `love` bindings as /usr/lib/urn/lib/love I can use `love` bindings freely after start `urn` compiler.

There is one thing that I was thinking: is better using /usr/lib or /usr/share? Because /usr/lib is indeed more for binaries and libraries dynamic and /usr/share for source-like files. Maybe /usr/share is better... but Python use /usr/lib as well. We need think a little about it. 

What you think about these things?

1. A way to install third-packages easily working fine as default
2. Use /usr/lib/ or /usr/share for urn language

PS.: why the name urn?

**Comment by zardyh** [comment]
> Use /usr/lib/ or /usr/share for urn language

The nix derivation that we ship with currently tacks our libraries under `$out/lib/urn/`, so presumably `/usr/lib` is where they'd go in a FHS system.

**Comment by SquidDev** [comment]
> I only saw that you prefer use GitLab instead GitHub after create this issue. I hope you don't mind to continue to track this issue here.

That's fine! I check both pretty regularly, so I'm not especially fussed.

> How we can handle the external packages of the urn language?

Hrmrmr, that's a fair point. Your suggested solution is pretty much what the nix derivation does so I'd be OK with that. Installing into the same directory feels a little weird, but it's what most languages do so I guess it's fine...

> Use /usr/lib/ or /usr/share for urn language

Lua uses `/usr/share` for source level files, so I just intimated them :). That being said, luarocks installs to `/usr/lib`, so goodness knows. I an alternative would be to use `/usr/share` for the core compiler/stdlib and then `/usr/lib` for external libraries.

> PS.: why the name urn?

I _think_ it's because @zardyh had a Lisp called café, and one uses an Urn to store hot drinks. I've reread through the chat logs and it's honestly not much clearer.

**Comment by ryukinix** [comment]
> Lua uses /usr/share for source level files, so I just intimated them :). That being said, luarocks installs to /usr/lib, so goodness knows. I an alternative would be to use /usr/share for the core compiler/stdlib and then /usr/lib for external libraries.

I like it.

**Comment by kress95** [comment]
> I think it's because @zardyh had a Lisp called café, and one uses an Urn to store hot drinks. I've reread through the chat logs and it's honestly not much clearer.

Interesting. Hey guys, I'm loving this little language, expect more hobby game devs using it with love. 😄

**Comment by ryukinix** [comment]
As we said at urn@freenode, we need to change the PKGBUILD path probably because another package conflict on namespace of the filesystem. There is a package called `urn-git` on AUR that relies on the availability of the path /usr/share/urn, which for now we'll are planning to use for the urn-lang.

SquidDev said that we should use that paths instead:

```
/usr/share/urn-lang :: for this repo
/usr/lib/urn-lang :: for the third packages
``` 

Also I would suggest to beyond the `/usr/lib/urn-lang` for third-package, would be nice have a non-root need write to add temporary pacakges at ~/.local/lib/urn-lang as Python does and other languages as well. That way users without super-user access can easily create as well packages and making available for whatever the reason of the user is.

**Comment by ryukinix** [comment]
@SquidDev since we have a functional PKGBUILD I can publish on AUR. Do you have any problem with it? You want that I wait something? Actually, you prefer being the owner of the AUR package?

Since I have some experience maintaining and publish AUR packages I can create and, if you have a AUR account, I can add you later as maintainer. Also, if you wish I can transfer the ownership as well. Earlier when I don't have experience with AUR, I wrote some Python libraries and utilities ([ryukinix/mal] and [ryukinix/decorating]), so another user created for me the AUR packages and added me as maintainer. One year later the user which created that packages on AUR need to pull-off from the development and transfer the ownership to me and this was completely ok.

Since we have a AUR package published, I think we are done with this issue. Thanks for all the attention. :)

[ryukinix/mal]: https://github.com/ryukinix/mal
[ryukinix/decorating]: https://github.com/ryukinix/decorating

**Comment by SquidDev** [comment]
@ryukinix If you'd be willing to do that, it would be wonderful. Thank you!

**Comment by ryukinix** [comment]
Nice to hear, I'll do that and I'll attach on this issue the link of the package. But, why this:

https://github.com/SquidDev/urn/blob/0f30095c58fcbd3d552c98b538d27dfad565e75d/PKGBUILD#L21-L25

There is some real need to do this twice? 🤔  I don't understand. It's a simple mistake? I can remove it here before publish on AUR if is it.

**Comment by SquidDev** [comment]
This is required when the code generation or optimisation ares of the compiler have changed. The first compile will result in a new compiler with those changes active. The second compile will result in a compiler built *using* the new code generation/optimiser: generally resulting in a faster or cleaner result.

**Comment by ryukinix** [comment]
Interesting! I'll add a little note as remainder for that. Thank you.

**Comment by ryukinix** [comment]
https://aur.archlinux.org/packages/urn-lang-git/
