### ISSUE TITLE
Do not advertise with minimalism

### ISSUE THREAD

**Issue by porky11** [SquidDev/urn#19]
The need of different kinds of brackets for pretty common things is not minimalistic.

**Comment by SquidDev** [comment]
The whole "minimalism" thing is something we've discussed a couple of times lately. It was definitely true a year ago, when Urn was taking its first steps, but is less applicable now. I generally view it that the "core language" - namely the [list of special forms](http://urn-lang.com/reference/02-special-forms.html) is comparatively small compared with most Lisps - it's pretty much 4 expressions + quotes + definitions. That being said, the standard library is most definitely not minimal...

As far as different brackets go, I'm slightly confused. Whilst `{}` can only be used to declare Lua tables, `()` and `[]` can be used interchangeably. For instance, this is equally valid Urn:

```cl
[let ([x 2]) 
  [+ x 1]]
```

The compiler/stdlib follows a set of conventions - namely use `[]` for bindings and conditions, but it isn't enforced anywhere.

**Comment by porky11** [comment]
So the different brackets are just there to attract Clojure users ;)

**Comment by SquidDev** [comment]
I can't deny that some parts of Urn are inspired by Clojure. In this case it was mostly because it gives some visual distinction to code blocks, and (IMO) makes some of the more deeply nested expressions easier to read.
