### ISSUE TITLE
How to set an element in a list?

### ISSUE THREAD

**Issue by sci4me** [SquidDev/urn#21]
How do you set the ith element of a list? set-idx!? I don't know how the implementation works, but I see that nth takes ["n"] into account and set-idx! doesn't..

**Comment by SquidDev** [comment]
`set-idx!` (or more commonly `.<` work). One can also use `setq!`, which handles negative indicies:

```lisp
> (define x '(1 2 3))
out = (1 2 3)
> (setq! (nth x 2) 23)
> x
out = (1 23 3)
```
