### ISSUE TITLE
Should bignum be renamed to bigint?

### ISSUE THREAD

**Issue by sci4me** [SquidDev/urn#31]
As far as I've been able to tell, it's really a BigInt library... not BigNum.

**Comment by CrazedProgrammer** [comment]
I can definitely see the use cases for it, but I think it would be really hard to implement.

You would either have to make an implementation of binary/decimal floating point math, or rational math (in this case you could reuse bigint), which are probably way harder than integer math. I don't have experience with writing floating point or rationals implementations.
I'm currently working on other projects ([one of which](https://github.com/CrazedProgrammer/CCBox) uses Urn), and I don't have much free time left to spare, so I don't see myself doing this in the next few months.

Though, if you want to do it yourself and make a PR (MR), be my guest :)
It would be a fun project which would make the Urn standard library stand out,

**Comment by plt-amy** [comment]
We already have [rational numbers](https://github.com/SquidDev/urn/blob/master/lib/math/rational.lisp), that's why compiled code's so freaking big out of the box, they just don't use big ints.
