### ISSUE TITLE
how does capturing multiple splices work?

### ISSUE THREAD

**Issue by AkashaP** [SquidDev/urn#34]
i dont know if this is a bug or not
say i have two lists (list 1 99999) and (list 1 2) and would like to join them together into a single list easily

the easiest way i know of doing it is
`> (flatten (list (list 1 99999) (list 1 2)))
out = (1 99999 1 2)`

another way is 
`> (with (res (list)) (for-each item (list 1 99999) (push! res item)) (for-each item (list 1 2) (push! res item)) res)
out = (1 99999 1 2)`

one way i thought would work, but doesn't, is 
`> (list @(list 1 99999) @(list 1 2))
out = (1 1 2)`
even though `(list @(list 1 99999)` returns `(list 1 99999)`

why doesn't the last way work? is it a bug or am i misunderstanding how splice works in this situation

**Comment by SquidDev** [comment]
So `@` effectively compiles to Lua's `table.unpack`, which only really does what you want when in the last position of a function call:

https://github.com/SquidDev/urn/blob/6e6717cf1376b0950e569e3771cb7e287aed291d/lib/core/base.lisp#L450-L455

However, what would work would be using a splice within a quasi-quote. So something like the following:

```lisp
> `(,@(list 1 99999) ,@(list 1 2))
out = (1 99999 1 2)
```

In this particular case you can even do `` `(,@'(1 99999) ,@'(1 2))`` for maximum glyph usage :).
