### ISSUE TITLE
Grammar?

### ISSUE THREAD

**Issue by ib00** [SquidDev/urn#37]
Is there a formal grammar description of Urn?

**Comment by SquidDev** [comment]
Sorry for not responding earlier - clearly missed this in a sea of notifications.

I'm afraid not. It's mostly just your normal lisp, with some additional bits of syntax:
 - `[EXPR*]` is equivalent to `(EXPR*)`
 - `{EXPR*}` is equivalent to `{struct-literal EXPR*}`.
 - Support for additional numeric literals: `#xFF`, `#b010101` and `#bXIV`

I suspect it wouldn't be too hard to turn this into a formal grammar, it just never seemed worth it.
