### ISSUE TITLE
Error in "Guess the number" tutorial

### ISSUE THREAD

**Issue by fuxoft** [SquidDev/urn#8]
This line:

`(import lua/os time)`

should instead be:

`(import lua/os (time))`

Otherwise it fails silently with `time` being still undefined.

BTW, is there a better place to report errors in documentation than here?

**Comment by SquidDev** [comment]
Thanks, good catch! 

> Is there a better place to report errors in documentation than here?

Sadly there isn't, though I'm welcome to suggestions. Unfortunately, documentation is something that has been rather neglected. Sorry.

**Comment by fuxoft** [comment]
I think your documentation is quite good, for a quite new two-person project. I know Lua pretty well, I wanted to learn more about Lisp and studying Urn sources is fascinating to me. Is there a general urn forum in which you are participating? I found about urn in Reddit / Lua post which was probably not made by you.

**Comment by SquidDev** [comment]
We have a [Gitter room](https://gitter.im/urn-lang/urn) which, whilst a bit of a mess, is the closest thing we have to a forum. Feel free to ask any questions there!

Gosh, I'm subscribed to /r/lua and totally missed that. Thanks for pointing it out.
