### ISSUE TITLE
Example of the macro -> not working

### ISSUE THREAD

**Issue by mdbrlh** [SquidDev/urn#9]
The [example](https://squiddev.github.io/urn/docs/lib.function.html) of the macro **->** seem not working
```
(-> '(1 2 3)
    succ
    (* <> 2))
```

A solution who return (4 6 8) :
```
(-> '(1 2 3)
    (map succ <>)
    (map (cut * <> 2) <>))
```

**Comment by SquidDev** [comment]
Fixed. Thanks for the report! Sorry for any confusion caused.
